name: Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Run Docker container
        run: |
          docker stop cloudtask-app-prod || true
          docker rm cloudtask-app-prod || true
          docker build -t cloudtask-app:latest -f backend/Dockerfile .
          docker run -d \
            --name cloudtask-app-prod \
            -p 8080:8080 \
            -e SPRING_MAIN_ALLOW_CIRCULAR_REFERENCES=true \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cloudtaskdb \
            -e SPRING_DATASOURCE_USERNAME=cloudtask_user \
            -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --restart unless-stopped \
            cloudtask-app:latest

      - name: Verify
        run: |
          docker ps | grep cloudtask-app-prod
          echo "✅ Deployed!"
